# Generated by Django 4.1.3 on 2023-02-01 11:21

import apps.restaurants.services
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='FoodType',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, unique=True, verbose_name='TypeName')),
            ],
        ),
        migrations.CreateModel(
            name='PaymentOptions',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=30, unique=True, verbose_name='PaymentName')),
            ],
        ),
        migrations.CreateModel(
            name='Restaurant',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, verbose_name='Name')),
                ('description', models.TextField(verbose_name='Description')),
                ('min_sum', models.FloatField(verbose_name='MinSum')),
                ('max_sum', models.FloatField(default=None, verbose_name='MaxSum')),
                ('website', models.CharField(max_length=100, verbose_name='Website')),
                ('phone', models.CharField(max_length=20, verbose_name='Phone')),
                ('parking_detail', models.CharField(max_length=100, verbose_name='ParkingDetail')),
                ('additional', models.CharField(max_length=150, verbose_name='Additional')),
                ('main_photo', models.ImageField(upload_to=apps.restaurants.services.restaurant_directory_path, verbose_name='MainPhoto')),
                ('food_type', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='restaurants', to='restaurants.foodtype')),
                ('payment_options', models.ManyToManyField(to='restaurants.paymentoptions')),
            ],
        ),
        migrations.CreateModel(
            name='RestaurantGalleryPhoto',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('short_name', models.CharField(max_length=30, verbose_name='PhotoName')),
                ('image', models.ImageField(upload_to=apps.restaurants.services.restaurant_directory_path, verbose_name='URL')),
                ('restaurant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='photos', to='restaurants.restaurant')),
            ],
        ),
    ]
