# Generated by Django 4.1.3 on 2022-12-01 10:15

from django.db import migrations, models
import django.db.models.deletion
import services.restaurant_service


class Migration(migrations.Migration):

    dependencies = [
        ('restaurants', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Restaurant',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, verbose_name='Name')),
                ('description', models.TextField(verbose_name='Description')),
                ('min_sum', models.FloatField(verbose_name='MinSum')),
                ('max_sum', models.FloatField(default=None, verbose_name='MaxSum')),
                ('website', models.CharField(max_length=100, verbose_name='Website')),
                ('phone', models.CharField(max_length=20, verbose_name='Phone')),
                ('parking_detail', models.CharField(max_length=100, verbose_name='ParkingDetail')),
                ('additional', models.CharField(max_length=150, verbose_name='Additional')),
                ('main_photo', models.ImageField(upload_to=services.restaurant_service.restaurant_directory_path)),
                ('food_type', models.ForeignKey(default=1, on_delete=django.db.models.deletion.SET_DEFAULT, related_name='restaurants', to='restaurants.foodtype')),
                ('payment_options', models.ManyToManyField(to='restaurants.paymentoptions')),
            ],
        ),
        migrations.CreateModel(
            name='RestaurantGalleryPhoto',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to=services.restaurant_service.restaurant_directory_path)),
                ('restaurant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='photos', to='restaurants.restaurant')),
            ],
        ),
    ]
