# Generated by Django 4.1.3 on 2022-12-07 12:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('restaurants', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='foodtype',
            name='name',
            field=models.CharField(max_length=50, unique=True, verbose_name='TypeName'),
        ),
        migrations.AlterField(
            model_name='paymentoptions',
            name='name',
            field=models.CharField(max_length=30, unique=True, verbose_name='PaymentName'),
        ),
    ]
