# Generated by Django 4.1.3 on 2022-12-08 10:38

from django.db import migrations, models
import services.restaurant_service


class Migration(migrations.Migration):

    dependencies = [
        ('restaurants', '0002_alter_foodtype_name_alter_paymentoptions_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='restaurantgalleryphoto',
            name='short_name',
            field=models.CharField(default='image', max_length=30, verbose_name='PhotoName'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='restaurant',
            name='main_photo',
            field=models.ImageField(upload_to=services.restaurant_service.restaurant_directory_path, verbose_name='MainPhoto'),
        ),
        migrations.AlterField(
            model_name='restaurantgalleryphoto',
            name='image',
            field=models.ImageField(upload_to=services.restaurant_service.restaurant_directory_path, verbose_name='URL'),
        ),
    ]
